### ISSUE TITLE
One-way calls lead to thread scope leak/accumulation

### ISSUE THREAD

**Issue by mpetazzoni** [opentracing-contrib/java-thrift#10]
The current code of the `SpanProtocol` assumes that a receive will always follow a write to close the tracing scope once the response has been received from the server. Unfortunately that's not always the case when you consider `oneway` endpoints.

@pavolloffay Any ideas on how to handle this?

**Comment by mpetazzoni** [comment]
I've done some more investigation on this today, and I've unfortunately come to the conclusion that this isn't possible from this library alone, given the hooks at our disposal from the Thrift library.

What I've ended up doing is to have clients use an extension of their client factory that looks like this:

```java
public class BetterClientFactory implements TServiceClientFactory<Client> {

    private final Tracer tracer;

    public BetterClientFactory(Tracer tracer) {
        this.tracer = tracer;
    }

    @Override
    public Client getClient(TProtocol prot) {
        return getClient(prot, prot);
    }

    @Override
    public Client getClient(TProtocol iprot, TProtocol oprot) {
        return new Client(iprot, oprot) {
            @Override
            protected void sendBaseOneway(String methodName, TBase<?, ?> args)
                    throws TException {
                try {
                    super.sendBaseOneway(methodName, args);
                } finally {
                    // Close the scope immediately after sending the one-way call.
                    Scope scope = tracer.scopeManager().active();
                    if (scope != null) {
                        scope.close();
                    }
                }
            }
        };
    }
}
```

Unfortunately, I don't think there is a way to make this reusable/generic. One could also use a `Proxy` class, but there are certain scenarios where that's not possible because the `Proxy` class will only appear to implement the `Iface`, and not appear to extend `TServiceClient`.

**Comment by pavolloffay** [comment]
@malafeev is the author here he might know more.

Maybe a solution could be to pass the span in attributes (if there are any) and just activate for interceptors/usercode (if there are any).

**Comment by malafeev** [comment]
how about 
```
class BetterClientFactory<T extends TServiceClient> implements TServiceClientFactory<T> {
....
}
```

**Comment by mpetazzoni** [comment]
@malafeev unfortunately you can't do `new T(iprot, oprot) { ... }`.

**Comment by malafeev** [comment]
fixed by checking message type
