### ISSUE TITLE
Trace context is included multiple times when Thrift messages involves sub-structures

### ISSUE THREAD

**Issue by mpetazzoni** [opentracing-contrib/java-thrift#12]
Because the trace context information is written in `writeFieldStop()`, it will be included at the end of each Thrift structure that gets encoded on the protocol. This is problematic when the request includes collections of other Thrift structures, as the trace context information will be added many many times at the end of each "object", adding a considerable amount of overhead to the network exchanges.

That being said, I'm not sure there is another way to do this given the hooks given to us by the `TProtocol` interface, unless there is somehow a way to use `writeMessageEnd()`?

**Comment by mpetazzoni** [comment]
Actually this is even more of a problem than I thought because of the logic in the `ServerProtocolDecorator`.

A new active span will be created every time one of those nested structures ends, and obviously all but one of those spans will never finish and they just linger in memory.

Given this and the issues brought up in #10, it makes this library mostly unusable for the following reasons:

* tracing of one-way calls leaks spans client-side
* tracing of async calls leaks spans client-side
* tracing of any requests that contains a collection of Thrift structures leaks many spans server-side, and incurs massive network overhead

**Comment by malafeev** [comment]
problem with sub-structures can be fixed with kind of span holder.

could you give more details about problem with async calls?

**Comment by mpetazzoni** [comment]
Can you elaborate on your idea for sub-structures? What do you mean by "kind of span holder"?

The problem with async calls is that, on the client side, the thread emitting the request is not the same as the thread receiving the response, and there is no apparent way to transfer the request's initial trace scope to the thread that will handle the response. With async Thrift calls, the request is prepared and the trace context serialized in the caller's thread (which is good), but the response is handled by the `TAsyncClientManager`'s `SelectThread`.

**Comment by malafeev** [comment]
I'm thinking to use `ThreadLocal` span holder:
- In `writeFieldStop` put span there if not exist, but if exists then don't create new span. 
- clear  ThreadLocal in `writeMessageEnd`

**Comment by mpetazzoni** [comment]
That would result in the trace context being added to whatever the first sub-structure is, instead of the enclosing request structure. Not particularly elegant :(

**Comment by malafeev** [comment]
hm, we can write trace context in `writeMessageBegin`

**Comment by malafeev** [comment]
@mpetazzoni it would be helpful to have tests demonstrating problems you found.
at least we can mention all limitations in README

**Comment by mpetazzoni** [comment]
It's probably possible to write it out in `writeMessageBegin`, as long as you're using the `TBinaryProtocol`. At this point of the serialization you're inside a "struct" yet though. This doesn't seem to be a problem with the `TBinaryProtocol` because it doesn't do anything in `writeStructBegin`, but other protocols may do different things. It's probably an acceptable limitation, but something that should be noted nonetheless.

As for tests, I don't have much time right now to write formal unit tests demonstrating the issues. A quick `tcpdump` will show you the problem of the trace context being serialized multiple times though. For the one-way issue, see #10 and the proposed workaround there. For the async issue, I've explained it above; doesn't really need a test to understand that the code in its current state simply does not support the async Thrift threading model.

**Comment by mpetazzoni** [comment]
Thanks for 0.0.7, looks like it does the trick! Still have to do some more thorough testing but it looks good so far!
