### ISSUE TITLE
needs to be backwards-compatible

### ISSUE THREAD

**Issue by bhs** [opentracing-contrib/java-thrift#2]
@malafeev IIRC (please correct me if I'm wrong), this approach requires that servers upgrade before clients. That is operationally sketchy/dangerous.

Am I missing something about the name-prepending-based approach?

An alternative would be to use a "magic" tag number within the top-level message. I would favor that approach for the forwards- and backwards-compatibility benefits.

**Comment by malafeev** [comment]
@bhs yes, servers must be upgraded first.
I didn't find any way how I can add "magic" tag into `TMessage` in ` TProtocol` on client side.
`org.apache.thrift.TMultiplexedProcessor` uses the same name-prepending-based approach.

**Comment by bhs** [comment]
@malafeev I agree that `TMultiplexedProcessor` requires the same rollout strategy, but it's still burdensome / problematic and can/should be avoided.

I believe the solution here would be to do something like the delegation for messages, but "down one level"... i.e., for the numbered fields within those messages. It's more code and thus harder to implement, but far less dangerous to deploy since Thrift is already designed to work when there are unrecognized numbered fields. Is there a reason that wouldn't work?

**Comment by malafeev** [comment]
got it :)

**Comment by bhs** [comment]
@malafeev thanks. It will be finicky but it's worth it :)

If you run into a brick wall and/or it's just not going to work for some reason, please circle back and let me know. I thought (?) this was feasible but maybe I'm missing something.
