### ISSUE TITLE
Designate constructor as a public to make SpanProtocol extendable

### ISSUE THREAD

**Issue by vitalifed** [opentracing-contrib/java-thrift#21]
https://github.com/opentracing-contrib/java-thrift/blob/5965b639b3a51e437a152337e422f8841cec7369/src/main/java/io/opentracing/thrift/SpanProtocol.java#L92

Please consider to designate constructor of **SpanProtocol**  as a public. I would leke to extend an implementation of the class or consider to replce inner class **Factory** with a builder instead to get rid of constructor telescoping. 

Thanks in advance!

**Comment by malafeev** [comment]
@vitalifed done

**Comment by vitalifed** [comment]
Thanks for the swift reply! 
Sorry, that I bother you again, but could you please update **SpanHolder** (make it public) since it's declared as default I can't actually extend **SpanProtocol** since it depends on **SpanHolder**

**Comment by malafeev** [comment]
@vitalifed done
