### ISSUE TITLE
Cut a 0.0.4 release?

### ISSUE THREAD

**Issue by mpetazzoni** [opentracing-contrib/java-thrift#5]
Hi @malafeev,

Thanks for the quick turnaround on merging #3 and #4! With those two fixes I got `java-thrift` to correctly trace my Thrift RPC calls, and pass along trace context from client to server as desired. Would you be willing to make a 0.0.4 release and deploy that to Maven Central? It would make dependency management much easier.

Thanks in advance!

**Comment by malafeev** [comment]
0.0.4 will be available in maven central in several hours. It takes time :)
